# @name register
POST https://rest.cmhvscode.dev/api/auth/register
Content-Type: application/json

{
  "email": "admin",
  "password": "user",
  "name": "admin"
}

###
# @name login
POST https://rest.cmhvscode.dev/api/auth/login
Content-Type: application/json

{
  "email": "admin",
  "password": "user"
}
###
@refreshToken = {{login.response.body.refreshToken}}

###
# @name refresh
GET https://vite.cmhvscode.dev/api/auth/refresh
Authorization: Bearer {{refreshToken}}

###
@accessToken = {{login.response.body.accessToken}}
###
# @name authTest
GET https://vite.cmhvscode.dev/api/auth/authTest
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
# @name userList
GET https://vite.cmhvscode.dev/api/auth/userList
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
# @name userInfo
GET https://vite.cmhvscode.dev/api/auth/userInfo
Content-Type: application/json
Authorization: Bearer {{accessToken}}